platform :ios, '13.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'MVVMSample' do
  use_frameworks!

  pod 'RxSwift',  '~> 5'
  pod 'RxCocoa',  '~> 5'
  pod 'RxSwiftExt'
  pod 'Alamofire'
end
